
import React, { useState, useEffect } from 'react';
import Layout from './components/Layout';
import ScanInterface from './components/ScanInterface';
import Dashboard from './components/Dashboard';
import VulnerabilityList from './components/VulnerabilityList';
import VulnerabilityDetail from './components/VulnerabilityDetail';
import { ScanResult, Vulnerability, ScanSettings } from './types';
import { ShieldCheck, Download, Trash2, Database, Loader2, History as HistoryIcon, ExternalLink } from 'lucide-react';

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState('dashboard');
  const [settings, setSettings] = useState<ScanSettings>(() => {
    const saved = localStorage.getItem('scan_settings');
    return saved ? JSON.parse(saved) : { deepThinking: true, autoRemediation: true };
  });
  
  const [scanHistory, setScanHistory] = useState<ScanResult[]>(() => {
    const saved = localStorage.getItem('scan_history');
    return saved ? JSON.parse(saved) : [];
  });

  const [lastScan, setLastScan] = useState<ScanResult | undefined>(() => {
    const saved = localStorage.getItem('last_scan');
    return saved ? JSON.parse(saved) : undefined;
  });

  const [selectedVuln, setSelectedVuln] = useState<Vulnerability | null>(null);
  const [isExporting, setIsExporting] = useState(false);

  useEffect(() => {
    localStorage.setItem('scan_settings', JSON.stringify(settings));
  }, [settings]);

  useEffect(() => {
    localStorage.setItem('scan_history', JSON.stringify(scanHistory));
  }, [scanHistory]);

  useEffect(() => {
    const handleNav = () => setActiveTab('scan');
    window.addEventListener('nav-scan', handleNav);
    return () => window.removeEventListener('nav-scan', handleNav);
  }, []);

  const handleScanComplete = (result: ScanResult) => {
    setLastScan(result);
    setScanHistory(prev => [result, ...prev].slice(0, 10)); // Keep last 10
    localStorage.setItem('last_scan', JSON.stringify(result));
    setActiveTab('dashboard');
  };

  const clearHistory = () => {
    if (confirm("Are you sure you want to wipe all session scan history?")) {
      setLastScan(undefined);
      setScanHistory([]);
      localStorage.removeItem('last_scan');
      localStorage.removeItem('scan_history');
    }
  };

  const loadFromHistory = (scan: ScanResult) => {
    setLastScan(scan);
    localStorage.setItem('last_scan', JSON.stringify(scan));
    setActiveTab('dashboard');
  };

  const exportReport = () => {
    if (!lastScan) return;
    setIsExporting(true);
    
    try {
      const markdown = `# Aegis AI Security Report
Generated on: ${new Date(lastScan.timestamp).toLocaleString()}
Target: ${lastScan.target}
Type: ${lastScan.targetType}

## Executive Summary
- Total Findings: ${lastScan.summary.total}
- Critical: ${lastScan.summary.critical}
- High: ${lastScan.summary.high}
- Medium: ${lastScan.summary.medium}
- Low: ${lastScan.summary.low}
- Info: ${lastScan.summary.info}

## Detailed Findings
${lastScan.findings.map(f => `
### [${f.severity}] ${f.title}
- **Category**: ${f.category}
- **Location**: ${f.location}
- **CWE**: ${f.cweId || 'N/A'}
- **Description**: ${f.description}
- **Remediation**: ${f.remediation}
`).join('\n---\n')}

*Generated by Aegis AI Security Scanner - OSINT Grounded Analysis*`;

      const blob = new Blob([markdown], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `aegis-report-${new Date().getTime()}.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (e) {
      console.error("Export failed", e);
    } finally {
      setTimeout(() => setIsExporting(false), 500);
    }
  };

  return (
    <Layout activeTab={activeTab} setActiveTab={setActiveTab}>
      <div className="max-w-7xl mx-auto pb-20">
        {activeTab === 'dashboard' && (
          <div className="space-y-8">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <h2 className="text-3xl font-bold text-white">Security Overview</h2>
                <p className="text-slate-400">Risk metrics for {lastScan?.target || 'no active target'}.</p>
              </div>
              {lastScan && (
                <div className="flex items-center gap-3">
                  <button 
                    onClick={exportReport}
                    disabled={isExporting}
                    className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 disabled:opacity-50 text-slate-200 text-sm font-semibold rounded-xl transition-all border border-slate-700 active:scale-95"
                  >
                    {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
                    Export Report
                  </button>
                  <button 
                    onClick={clearHistory}
                    className="flex items-center gap-2 px-4 py-2 bg-red-900/20 hover:bg-red-900/40 text-red-400 text-sm font-semibold rounded-xl transition-all border border-red-900/30 active:scale-95"
                  >
                    <Trash2 className="w-4 h-4" /> Wipe
                  </button>
                </div>
              )}
            </div>
            
            <Dashboard lastScan={lastScan} />
            
            {lastScan && (
              <div className="pt-8">
                <div className="flex items-center justify-between mb-6">
                  <h3 className="text-xl font-bold text-white flex items-center gap-2">
                    <Database className="w-5 h-5 text-blue-500" />
                    Vulnerabilities Log
                  </h3>
                  <div className="text-xs text-slate-500 bg-slate-900 px-3 py-1 rounded-full border border-slate-800">
                    Showing {lastScan.findings.length} findings
                  </div>
                </div>
                <VulnerabilityList 
                  findings={lastScan.findings} 
                  onSelect={setSelectedVuln} 
                />
              </div>
            )}
          </div>
        )}

        {activeTab === 'scan' && (
          <ScanInterface onScanComplete={handleScanComplete} settings={settings} />
        )}

        {activeTab === 'history' && (
          <div className="space-y-6 animate-in fade-in duration-500">
            <div className="flex items-center justify-between mb-8">
              <div>
                <h2 className="text-3xl font-bold text-white">Audit History</h2>
                <p className="text-slate-400">Previous security assessments from this session.</p>
              </div>
              <button 
                onClick={clearHistory}
                className="text-slate-500 hover:text-red-400 text-sm flex items-center gap-2"
              >
                <Trash2 className="w-4 h-4" /> Clear History
              </button>
            </div>

            {scanHistory.length === 0 ? (
              <div className="text-center py-20 bg-slate-900/50 border border-slate-800 rounded-2xl border-dashed">
                <HistoryIcon className="w-12 h-12 text-slate-700 mx-auto mb-4" />
                <p className="text-slate-500">No scans recorded in this session.</p>
              </div>
            ) : (
              <div className="grid gap-4">
                {scanHistory.map((scan, i) => (
                  <div 
                    key={i} 
                    onClick={() => loadFromHistory(scan)}
                    className="p-6 bg-slate-900 border border-slate-800 rounded-2xl hover:border-blue-600 transition-all cursor-pointer group flex items-center justify-between"
                  >
                    <div className="flex items-center gap-6">
                      <div className={`p-4 rounded-xl ${scan.summary.critical > 0 ? 'bg-red-500/10 text-red-500' : 'bg-slate-800 text-slate-400'}`}>
                        <ShieldCheck className="w-6 h-6" />
                      </div>
                      <div>
                        <div className="flex items-center gap-2 mb-1">
                          <span className="text-xs font-mono text-blue-500 uppercase">{scan.targetType}</span>
                          <span className="text-[10px] text-slate-600">•</span>
                          <span className="text-[10px] text-slate-500">{new Date(scan.timestamp).toLocaleString()}</span>
                        </div>
                        <h4 className="text-white font-bold group-hover:text-blue-400 transition-colors truncate max-w-md">{scan.target}</h4>
                      </div>
                    </div>
                    <div className="flex items-center gap-10">
                      <div className="flex gap-4">
                        <div className="text-center">
                          <p className="text-[10px] text-slate-600 uppercase font-bold">Findings</p>
                          <p className="text-lg font-bold text-white">{scan.summary.total}</p>
                        </div>
                        <div className="text-center">
                          <p className="text-[10px] text-red-600 uppercase font-bold">Critical</p>
                          <p className="text-lg font-bold text-red-500">{scan.summary.critical}</p>
                        </div>
                      </div>
                      <ExternalLink className="w-5 h-5 text-slate-700 group-hover:text-blue-500 transition-all" />
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {activeTab === 'settings' && (
          <div className="max-w-2xl bg-slate-900 border border-slate-800 rounded-2xl p-8 shadow-2xl animate-in slide-in-from-bottom-4">
            <h3 className="text-xl font-bold text-white mb-6">Aegis Configuration</h3>
            <div className="space-y-6">
              <div className="flex items-center justify-between p-4 bg-slate-950 rounded-xl border border-slate-800">
                <div>
                  <p className="text-white font-medium">Deep Thinking</p>
                  <p className="text-xs text-slate-500">Enable advanced reasoning and double-pass verification for high-accuracy SAST.</p>
                </div>
                <button 
                  onClick={() => setSettings(s => ({...s, deepThinking: !s.deepThinking}))}
                  className={`w-12 h-6 rounded-full relative transition-colors duration-200 ${settings.deepThinking ? 'bg-blue-600' : 'bg-slate-700'}`}
                >
                  <div className={`absolute top-1 w-4 h-4 bg-white rounded-full transition-all duration-200 ${settings.deepThinking ? 'right-1' : 'left-1'}`}></div>
                </button>
              </div>
              <div className="flex items-center justify-between p-4 bg-slate-950 rounded-xl border border-slate-800">
                <div>
                  <p className="text-white font-medium">Auto-Remediation</p>
                  <p className="text-xs text-slate-500">Automatically generate code fixes and diffs for discovered risks.</p>
                </div>
                <button 
                  onClick={() => setSettings(s => ({...s, autoRemediation: !s.autoRemediation}))}
                  className={`w-12 h-6 rounded-full relative transition-colors duration-200 ${settings.autoRemediation ? 'bg-blue-600' : 'bg-slate-700'}`}
                >
                  <div className={`absolute top-1 w-4 h-4 bg-white rounded-full transition-all duration-200 ${settings.autoRemediation ? 'right-1' : 'left-1'}`}></div>
                </button>
              </div>
            </div>
            <div className="mt-8 pt-6 border-t border-slate-800">
               <p className="text-xs text-slate-600 italic">
                 Security Note: Scan data is stored in your browser's localStorage. Your code and targets are sent only to the Aegis API for analysis — never stored server-side.
               </p>
            </div>
          </div>
        )}
      </div>

      {selectedVuln && (
        <VulnerabilityDetail 
          vuln={selectedVuln} 
          onClose={() => setSelectedVuln(null)} 
        />
      )}
    </Layout>
  );
};

export default App;
